### ISSUE TITLE
使用-du报错

### ISSUE THREAD

**Issue by admin-set** [Funsiooo/chunsou#2]
已经执行 pip3 install -r requirements.txt

使用 -u 正常
但是使用 -du 报错。截图如下

<img width="1824" alt="image" src="https://github.com/Funsiooo/chunsou/assets/63496176/0dbc3321-14f8-4016-ac63-7cba773ad270">

**Comment by Funsiooo** [comment]
Copy that！

**Comment by sasosos** [comment]
不知道咋回事，库一直安装不成功，你们有这问题吗

**Comment by Funsiooo** [comment]
已修复，上传异常导致缺少部分文件，重新下载试一下，感谢反馈！

**Comment by Funsiooo** [comment]
已修复，上传异常导致丢失部分文件，重新下载试一下，感谢反馈！

**Comment by Funsiooo** [comment]
已修复，上传异常导致丢失部分文件，项目已更新，可下载新版本进行使用，感谢反馈！

**Comment by sasosos** [comment]
![image](https://github.com/Funsiooo/chunsou/assets/59545651/026283bc-20bb-48b8-95d0-2b8c767b09da)

**Comment by sasosos** [comment]
![c43517081bcf6093eb433c40233f4cc](https://github.com/Funsiooo/chunsou/assets/59545651/bff95a46-4139-404e-98e7-8e7ef3d3ebb9)

**Comment by Funsiooo** [comment]
> ![c43517081bcf6093eb433c40233f4cc](https://user-images.githubusercontent.com/59545651/252262518-bff95a46-4139-404e-98e7-8e7ef3d3ebb9.png)

你先看有没有影响使用，若不影响可忽略！
