### ISSUE TITLE
python chunsou.py -du baidu.com

### ISSUE THREAD

**Issue by chenchen123423** [Funsiooo/chunsou#3]
14:16:36 [-] Error occurred , Check whether the network, command, or configuration is correct.

你好 报这个错误我需要修改什么配置吗

**Comment by Funsiooo** [comment]
如果是子域名爆破功能无法调用，该问题已修复，可下载新版本进行使用，若不是该问题，请截图反馈问题，感谢反馈！

**Comment by chenchen123423** [comment]
![图片](https://github.com/Funsiooo/chunsou/assets/115337466/3b707448-dac6-4854-8b2e-0cb2efba957e)

**Comment by Nightingle-yeying** [comment]
最新版也是这个报错，请问LZ解决了吗
