### ISSUE TITLE
不知道咋回事，库一直安装不成功，你们有这问题吗

### ISSUE THREAD

**Issue by admin-set** [Funsiooo/chunsou#4]
不知道咋回事，库一直安装不成功，你们有这问题吗

_Originally posted by @sasosos in https://github.com/Funsiooo/chunsou/issues/2#issuecomment-1627961917_
            你倒是说说啥库安装不成功呀，或者丢截图呀

**Comment by sasosos** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Funsiooo/chunsou"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月10日(星期一) 下午2:44
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;[Funsiooo/chunsou] 不知道咋回事，库一直安装不成功，你们有这问题吗 (Issue #4)





           不知道咋回事，库一直安装不成功，你们有这问题吗  
Originally posted by @sasosos in #2 (comment)
 你倒是说说啥库安装不成功呀，或者丢截图呀

**Comment by ahuyuhy** [comment]
Wappalyzer库 pip安装看着没问题 但是一直说缺
![image](https://github.com/Funsiooo/chunsou/assets/107756112/0a394349-2ed3-4071-b895-e55225029834)

**Comment by Funsiooo** [comment]
> Wappalyzer库 pip安装看着没问题 但是一直说缺 ![image](https://user-images.githubusercontent.com/107756112/252529008-0a394349-2ed3-4071-b895-e55225029834.png)

安装命令是这个 pip3 install python-Wappalyzer

**Comment by ahuyuhy** [comment]
> > Wappalyzer库 pip安装看着没问题 但是一直说缺 ![image](https://user-images.githubusercontent.com/107756112/252529008-0a394349-2ed3-4071-b895-e55225029834.png)
> 
> 安装命令是这个 pip3 install python-Wappalyzer

感谢 已解决

**Comment by whocansee** [comment]
我也有这个问题，这是报错信息：
`Collecting zope.interface==5.5.2 (from -r requirements.txt (line 101))
  Using cached zope.interface-5.5.2-cp311-cp311-win_amd64.whl (211 kB)
Collecting zstandard==0.17.0 (from -r requirements.txt (line 102))
  Using cached zstandard-0.17.0.tar.gz (629 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\nsfocus\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-e8dq6iy5\zstandard_e18ec174dd844a55973bff6a7d8bdaea\setup_zstd.py", line 66, in get_c_extension
          compiler.initialize()
        File "C:\Users\xxxs\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-mmfxuom_\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by whocansee** [comment]
这是运行的报错：
PS C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version> python .\chunsou.py -u http://127.0.0.1
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\chunsou.py", line 13, in <module>
    from modules.api.fofa import fofa_main
  File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\modules\api\fofa.py", line 32, in <module>
    import requests
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py", line 60, in <module>
    from . import utils
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
顺便问下，指纹库里keyword多个元素之间的匹配规则是and还是or？

**Comment by HuyaThomas** [comment]
各种报错，到ERROR: Could not find a version that satisfies the requirement pypiwin32==304 (from versions: 219, 223)放弃了。

**Comment by Funsiooo** [comment]
> 各种报错，到ERROR: Could not find a version that satisfies the requirement pypiwin32==304 (from versions: 219, 223)放弃了。

方便留个系统版本吗，这边测试环境windows10以及ubuntu没发现存在什么问题

**Comment by Funsiooo** [comment]
> 这是运行的报错： PS C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version> python .\chunsou.py -u http://127.0.0.1 Traceback (most recent call last): File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\chunsou.py", line 13, in from modules.api.fofa import fofa_main File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\modules\api\fofa.py", line 32, in import requests File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests__init__.py", line 60, in from . import utils File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 32, in from .cookies import cookiejar_from_dict File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\cookies.py", line 172, in class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping): ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'collections' has no attribute 'MutableMapping' 顺便问下，指纹库里keyword多个元素之间的匹配规则是and还是or？

and 而且暂时不支持大小写

**Comment by whocansee** [comment]
> > 这是运行的报错： PS C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version> python .\chunsou.py -u http://127.0.0.1 Traceback (most recent call last): File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\chunsou.py", line 13, in from modules.api.fofa import fofa_main File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\modules\api\fofa.py", line 32, in import requests File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests__init__.py", line 60, in from . import utils File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 32, in from .cookies import cookiejar_from_dict File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\cookies.py", line 172, in class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping): ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'collections' has no attribute 'MutableMapping' 顺便问下，指纹库里keyword多个元素之间的匹配规则是and还是or？
> 
> and 而且暂时不支持大小写

不支持大小写的意思是不支持区分大小写吗？

**Comment by Funsiooo** [comment]
> > > 这是运行的报错： PS C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version> python .\chunsou.py -u http://127.0.0.1 Traceback (most recent call last): File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\chunsou.py", line 13, in from modules.api.fofa import fofa_main File "C:\Users\xxx\Downloads\chunsou-1.1_version\chunsou-1.1_version\modules\api\fofa.py", line 32, in import requests File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests__init__.py", line 60, in from . import utils File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 32, in from .cookies import cookiejar_from_dict File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\cookies.py", line 172, in class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping): ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'collections' has no attribute 'MutableMapping' 顺便问下，指纹库里keyword多个元素之间的匹配规则是and还是or？
> > 
> > 
> > and 而且暂时不支持大小写
> 
> 不支持大小写的意思是不支持区分大小写吗？

是的，需要完全匹配

**Comment by whocansee** [comment]
> 

我有点混乱了，完全匹配意思是指强制区分大小写吧= =

**Comment by Funsiooo** [comment]
不好意思，我表述有问题，就是指纹里面的信息需要完全匹配，大小写均需一致

**Comment by whocansee** [comment]
> 不好意思，我表述有问题，就是指纹里面的信息需要完全匹配，大小写均需一致

谢谢回复！

**Comment by Funsiooo** [comment]
依赖安装异常问题已优化，可替换为新的 requirements.txt 进行安装使用！

**Comment by whocansee** [comment]
> 不好意思，我表述有问题，就是指纹里面的信息需要完全匹配，大小写均需一致

你好，我还有一个疑问：指纹库里的ico_hash使用哪一个哈希算法计算的？
