### ISSUE TITLE
报错，如下

### ISSUE THREAD

**Issue by 12498802** [Funsiooo/chunsou#5]
依赖安装成功，执行单个网站指纹检测时报错，如下，modules文件夹和chunsou.py在同一级目录中。modules目录中的文件没有动过。
D:\tool\Python3>python --version
Python 3.9.5

D:\tool\Python3>python webzhiwen\chunsou.py -u http://oa-new.xxxxxxxxxxx.cn
Traceback (most recent call last):
  File "D:\tool\Python3\webzhiwen\chunsou.py", line 10, in <module>
    from modules.core.banner import banner,banner_2
ModuleNotFoundError: No module named 'modules.core'; 'modules' is not a package

D:\tool\Python3>

**Comment by Funsiooo** [comment]
尝试根目录下执行脚本，避免调用文件异常 python chunsou.py -u http://xxx.xxx.xxx

**Comment by 12498802** [comment]
刚试了，还是报同样的错误。与目录无关哦，因为他们在同一级目录里面。
D:\tool\Python3>python chunsou.py -u http://xxxxxxxx.cn
Traceback (most recent call last):
  File "D:\tool\Python3\chunsou.py", line 10, in <module>
    from modules.core.banner import banner,banner_2
ModuleNotFoundError: No module named 'modules.core'; 'modules' is not a package

**Comment by Funsiooo** [comment]
这边重新测试没问题，你尝试重新安装依赖，看是否是网络问题依赖安装不完全！
