### ISSUE TITLE
关于-du参数的问题

### ISSUE THREAD

**Issue by sanxiu0** [Funsiooo/chunsou#8]
在单个url爆破子域名时，出现错误[-] Error occurred , Check whether the network, command, or configuration is correct.，其他模块功能正常
![image](https://github.com/Funsiooo/chunsou/assets/57577636/b1a2b271-e8e3-494e-88ab-b7c1991dd62c)
请问这是什么原因

**Comment by sanxiu0** [comment]
此前我已更换过多种网络环境

**Comment by Funsiooo** [comment]
你看一下 modules/plugins/OneForAll/config 路径下是不是一共有5个 py 文件，看是否是缺少了部分文件

**Comment by 115955615407** [comment]
我也有这个问题
![Uploading 1695374616155.png…]()
![1695374648884](https://github.com/Funsiooo/chunsou/assets/77622708/ffb3938f-14c9-42c6-8870-b2999de66cb0)
OneForAll单独用没问题

**Comment by Funsiooo** [comment]
done
